var initializeGame = require('./initializeGame');
initializeGame("abc",[
	{
		"question":"Who is Sachin Tendulkar?",
		"correctOption": "Cricketer",
		"options": ["Doctor",
					"Cricketer",
					"Engineer",
					"Lawyer"
		]
},
	{"question":"Start spreading the news, I’m leaving today” are the opening lines of which song?",
	"correctOption": "Closer",
	"options": [	"Latch",
					"Closer",
					"All The Way Up",
					"I Want You"
		]
},
	{"question":'In which television programme was I don’t believe it a catchphrase?',
	"correctOption": "House Of Cards",
	"options": [	"Friends",
					"Quantico",
					"Seinfield",
					"House Of Cards"
		]},
	{"question":'You Give Love a Bad Name and Livin’ on a Prayer were early hits for which band?',
	"correctOption": "The Beatles",
"options": [		"The Beatles",
					"Rolling Stones",
					"Pilot",
					"U2"
		]},
	{"question":'What was the surname of Del Boy and Rodney in Only Fools and Horses?',
	"correctOption": "Stifler",
"options": [		"Stifler",
					"Adams",
					"Gomez",
					"Hendricks"
		]},
	{"question":'In which year was a cinematic Space Odyssey set?',
	"correctOption": "2012",
"options": [		"2012",
					"2013",
					"2014",
					"2015"
		]},
	{"question":'Who was the lead singer of T. Rex?',
	"correctOption": "Bob James",
"options": [		"Bob James",
					"Peter",
					"Chris",
					"Jack"
		]},
	{"question":'Which silent movie actor created “The Little Tramp” character?',
	"correctOption": "Charlie Chaplin",
"options": [		"Charlie Chaplin",
					"Peter",
					"Jason",
					"Chris"
		]},
	{"question":'In which film does the line “Toto, I’ve a feeling we’re not in Kansas anymore” appear?',
	"correctOption": "Crew",
"options": [		 "Crew",
					"Heat",
					"Office",
					"Hemlet"
		]},
	{"question":'Who plays Lewis in Morse and its spin-off, Lewis?',
	"correctOption": "Not You",
"options": ["Him",
					"Not You",
					"That Guy",
					"No One"
		]},
	{"question":'What is Indiana Jones’s profession?',
	"correctOption": "Archaeologist",
"options": ["Archaeologist",
					"Doctor",
					"Engineer",
					"Lawyer"
		]},
	{"question":'Which policeman was at the centre of the Pink Panther movies?',
	"correctOption": "Travis",
"options": ["Travis",
					"Keith",
					"Chris",
					"Joey"
		]},
	{"question":'Which musical instruments are also called Kettledrums?',
	"correctOption": "Turn-Table",
"options": ["Keyboard",
					"Guitar",
					"Turn-Table",
					"Drums"
		]},
	{"question":'Some Enchanted Evening, Happy Talk and There is Nothing Like a Dame are songs from which musical?',
	"correctOption": "Some Love",
"options": ["Some Love",
					"Kickstart",
					"The Woman",
					"Can't Stay"
		]},
	{"question":'Which long-running Australian series is set in Summer Bay?',
	"correctOption": "Victoria Bash",
"options": ["Victoria Bash",
					"Melbourne Bash",
					"Sydney Bash",
					"Canberra Bash"
		]},
	{"question":'In which film does a farmer played by Kevin Costner build a baseball diamond in his cornfield?',
	"correctOption": "Moneyball",
"options": ["Moneyball",
					"Brookeback Mountain",
					"Taken",
					"Push"
		]},
	{"question":'Fox Mulder and Dana Scully were the main characters in which television series?',
	"correctOption": "NCIS",
"options": ["NCIS",
					"The Wanted",
					"Kids",
					"Players"
		]},
	{"question":'Which former schoolteacher from Neath has become a big-selling singer?',
	"correctOption": "Blake Shelton",
"options": ["Blake Shelton",
					"Chris Rock",
					"Kid Cudi",
					"Drake"
		]},
	{"question":'Who played Maximus Decimus Meridius in a 2000 Ridley Scott film?',
	"correctOption": "Meg Ryan",
"options": ["Meg Ryan",
					"Ridley",
					"Brad Pitt",
					"Chris Tucker"
		]},
	{"question":'How many red balloons did Nena take into the pop charts?',
	"correctOption": "6",
"options": ["6",
					"2",
					"12",
					"10"
		]},
	{"question":'Which of the Muppets did a stand-up comedy routine which tended not to be particularly good?',
	"correctOption": "Pup",
"options": ["Pup",
					"Cole",
					"Dylan",
					"Lewis"
		]},
	{"question":'In what sort of music might you hear scat singing?',
	"correctOption": "Reggae",
"options": ["Reggae",
					"Electronic",
					"Hip-Hop",
					"lawyer"
		]},
	{"question":'Which television series is set in William McKinley High School, Lima, Ohio?',
	"correctOption": "Glee",
"options": ["Glee",
					"24",
					"The Vampire Diaries",
					"The Walking Dead"
		]},
	{"question":'With which band did Pete Doherty come to fame?',
	"correctOption": "Daughtry",
"options": ["Daughtry",
					"One Republic",
					"Papa Roach",
					"Linkin Park"
		]},
	{"question":'Which soap opera started in 1972, and lost a word from its title in 1989?',
	"correctOption": "Seinfield",
"options": ["Seinfield",
					"The Comedy Show",
					"The Office",
					"The Wire"
		]},
	{"question":'What started with Sergeant in 1958 and ended with Columbus in 1992?',
	"correctOption": "Engineer",
"options": ["Doctor",
					"Cricketer",
					"Engineer",
					"lawyer"
		]},
	{"question":'What is the name of the character played by Michael Douglas in the Wall Street films?',
	"correctOption": "Charlie",
"options": ["Charlie",
					"Douglas",
					"Dirk",
					"Kirk"
		]},
	{"question":'From which opera does the March of the Toreadors come?',
	"correctOption": "Singin In The Rain",
"options": ["Singin In The Rain",
					"Black Swan",
					"The Graduate",
					"The Bachelor"
		]},
	{"question":'Who played the Vicar of Dibley?',
	"correctOption": "Christian",
"options": ["Christian",
					"Duncan",
					"Drake",
					"Steve"
		]},
	{"question":'What are the surnames of the title characters in Romeo and Juliet?',
	"correctOption": "Saint",
"options": ["Saint",
					"D'Souza",
					"Douglas",
					"Jones"
		]}],

	["srini","vishant","lal jose"],[0,0,0]);


